data_folder_paths:
  html_folder_path: /home/tamil/work/skunkworks/buffet-gpt/src/buffet_sink/html/
  pdf_folder_path: /home/tamil/work/skunkworks/buffet-gpt/src/buffet_sink/pdf/

chunking:
  chunk_size: 1000
  chunk_overlap: 200

embeddings:
  model: voyage-4-large

vector_store:
  path: /home/tamil/work/skunkworks/buffet-gpt/qdrant_storage
  collection_name: buffet_letters
  vector_size: 1024